### PR TITLE
Add exitcode 1 if crash is found (ZestDriver)

### PR DESCRIPTION
**Pull request by yevgenypats**
Add exitcode 1 if crash is found in ZestDriver just like in the maven plugin

### CODE REVIEW

**Comment by yevgenypats** [comment]
https://github.com/rohanpadhye/jqf/issues/50

**Comment by rohanpadhye** [comment]
If the exit code is added unconditionally, then all the other drivers (AFLDriver, PerfFuzzDriver, ReproDriver, RandomDriver, etc) will also have to be made consistent. Since EXIT_ON_CRASH is only defined for ZestDriver, relying on that flag will help isolate this behavior to only this driver.

**Comment by yevgenypats** [comment]
done

**Comment by rohanpadhye** [comment]
Thanks!

**Pull request merged**
