### PR TITLE
Fixed JavaScript assignment operators generating error statements

### PR DESCRIPTION
**Pull request by anfreshman**
#246 
hello, I want to try to fix this problem. I defined a new assignment statement generator, removed the assignment operator from BINARY_TOKENS, and added the latest assignment operator. I am not reproducing the above problem in the new version, so I think I have fixed the problem. I would appreciate it if you could review the code to confirm whether this pr can be merged, or if necessary, could you let me know what other necessary tests need to be performed？

### CODE REVIEW

**Comment by rohanpadhye** [comment]
Thanks for the contribution! I'll review this when I get some free cycles next, and merge if all looks good.

**Comment by rohanpadhye** [comment]
Looks good at first glacne! However, I noticed that while your code produces correct assignment statements of the form:
```
x = <expr>
```

It cannot produce assignment statements like this:
```
x[i] = <expr>
```

or:
```
x.a = <expr>
```

Can you update the `generateAssignmentNode` method to choose between identNode, objectProperty, or indexNode at the LHS?

Thanks.

**Comment by anfreshman** [comment]
Thanks for pointing out my problem！ I have updated and submitted a new version of the code.   I noticed that generatePropertyNode and generateIndexNode already existed in the original code to generate objectProperty and indexNode, so I reused these two methods and randomly selected them among the three lhstype types.   I would really appreciate it if you could review my code again

**Review by rohanpadhye — APPROVED** [review]
This looks great! Thanks.

**Comment by anfreshman** [comment]
Thanks！I am very happy to see this comment. Will this pr trigger the merge process next?

**Pull request merged**
