### PR TITLE
zest maven plugin: parameter to disable the statistics console output 

### PR DESCRIPTION
**Pull request by Ahmedfir**
This feature has only been implemented for the maven plugin.
For all other access points to zest (driver and cli) the statistics output remains always enabled.

### CODE REVIEW

**Comment by Ahmedfir** [comment]
@rohanpadhye I totally agree with you. I was thinking the same when doing it this way...  
I can't promise when exactly I can do it. Maybe somewhen this week. I will ping you whenever I start working on it. But of course if you're available before me, don't hesitate to assign the issue to you and work on it. :)

**Comment by Ahmedfir** [comment]
@rohanpadhye I just wanted to keep you updated: I am sorry but I don't think I will have time any-soon to do these changes. I will come back to it once I have room.
By the way, as there's multiple logging ways (the plot_data, the fuzzing.log, the console output) I thought it would be nice to have a -D flag for each one of them. What do you think about it?

**Comment by rohanpadhye** [comment]
No problem. I agree that controlling output via options is probably a good idea. I'll make an issue to revamp the controls for logging (while keeping the default behavior the same as current). Thanks!

**Comment by rohanpadhye** [comment]
Added support for `-Dquiet=true` in master.

**Pull request closed without merging**
