### PR TITLE
Add Trophies to README so people can easily add them via PR

### PR DESCRIPTION
**Pull request by yevgenypats**
I think one of the most important things for quicker adoption is how many bugs it found so I think
it would be better to add them straight to the readme and this way people can easily add more bugs via PRs unlike the wiki which you can't open a PR to.

I took some inspiration from [go-fuzz](https://github.com/dvyukov/go-fuzz#trophies) README which is quite popular.

### CODE REVIEW

**Comment by rohanpadhye** [comment]
That's a good suggestion! How would you suggest handling the wiki page? There is information that is being duplicated if we keep lists in both the README and in the wiki. Also, there are two links to the wiki trophy page from the README. Maybe those links should be updated to point to #trophies on the same page, so that the wiki page could be removed?

**Comment by yevgenypats** [comment]
Yes I think I will remove the link to the wiki page and we can link the wiki to the readme #trophies

**Comment by yevgenypats** [comment]
Updated the PR. should I update the Wiki?

**Comment by rohanpadhye** [comment]
I updated another link in the README. Let's not remove the bug list from wiki page completely, because I have some other links outside of GitHub that point to that page. We can simply add a thing at the top that says that the list is out of date and redirect to the README instead.

**Pull request merged**
